module.exports = {
	Name: "fakenews",
	Aliases: null,
	Author: "supinic",
	Cooldown: 10000,
	Description: "Randomly creates fake news headlines from existing presets. These are not real, and are supposed to be light-hearted and just a joke. Don't take them seriously.",
	Flags: ["mention","pipe"],
	Params: null,
	Whitelist_Response: null,
	Static_Data: (() => {
		this.data.previousHeadlines = [];

		return {
			repeats: 5,
			construct: {
				action: [
					"ANNIHILATES THEM WITH LOGIC",
					"BEATS THEM AT THEIR OWN GAME IN A GONE HOME SPEEDRUN",
					"BEATS THEM AT THEIR OWN GAME IN A LIFE IS STRANGE SPEEDRUN",
					"BEATS THEM IN A FIST FIGHT",
					"BEATS THEM IN A MELEE TOURNAMENT",
					"BEATS THEM IN DBFZ",
					"BEATS THEM IN DOTA",
					"BEATS THEM IN STARCRAFT",
					"BEATS THEM IN STREET FIGHTER",
					"BEATS THEM IN TEKKEN",
					"COMES DOWN HARD",
					"DESTROYS THEM WITH ANIME POWER",
					"DESTROYS THEM WITH REASON",
					"ENSNARES THEM IN A LOGIC TRAP",
					"OWNS THEM WITH WESTERN VALUES",
					"SHUTS THEM DOWN",
					"SLAUGHTERS THEM IN DEBATE",
					"STRIKES BACK",
					"TEACHES THEM A LESSON",
					"FIGHTS BACK"
				],
				adjA: [
					"BIASED",
					"CORRUPT",
					"DISHONEST",
					"EMOTIONAL",
					"FAKE GAMER",
					"FREE SPEECH HATING",
					"GAY",
					"HYSTERICAL",
					"LOOTBOX LOVING",
					"RACIST",
					"SKILLLESS",
					"SOY LOVING",
					"STUPID",
					"LOW T"
				],
				adjB: [
					"BRAVE",
					"HONEST",
					"INNOCENT",
					"UNBIASED"
				],
				clickbait: [
					"(Get woke go broke!)",
					"/v/ STRIKES BACK",
					"BRIE LARSON GETS EXPOSED?",
					"BUZZFEED SALTY?",
					"FEMALES REKT",
					"FEMINISM DESTROYED",
					"FEMINISM EXPLAINED",
					"FEMINISM SHUT DOWN?",
					"FEMINIST TEARS",
					"FREE SPEECH UNDER ATTACK",
					"HERE'S WHY",
					"I'M DONE WITH TRYING",
					"JAPAN RIDES AGAIN",
					"JAPAN STRIKES BACK",
					"MORE LIKELY THAN YOU THINK",
					"THE FULL STORY",
					"THE PROBLEM WITH [adjA] FEMALES IN 2020",
					"THE SJW PROBLEM",
					"WHITE CHILDREN UNDER THREAT",
					"[peopleB] CHIMES IN",
					"THE PROBLEM WITH [adjA] BLACK PEOPLE IN 2020"
				],
				groupA: [
					"BLUE CHECKMARKED TWITTER USERS",
					"COLLEGE STUDENTS",
					"COMMUNISTS",
					"CULTURAL MARXISTS",
					"FAKE GAMERS",
					"FEMINAZIS",
					"FEMINISTS",
					"GAME JOURNALISTS",
					"GAMER GIRLS",
					"LEFTIST ACTIVISTS",
					"LEFTISTS",
					"MARXISTS",
					"NAUGHTY DOG DEVS",
					"PEOPLE WHO CHEAT IN SEKIRO",
					"POSTMODERN NEO MARXISTS",
					"PRIDE MARCHERS",
					"SJWS",
					"WOMEN",
					"ANTIFA SOYBOYS",
					"BETAS",
					"BLACK DISABLED TRANSGENDERS",
					"BLACKS",
					"DISABLED PEOPLE",
					"TRANSGENDERS"
				],
				groupB: [
					"/pol/ USERS",
					"CIS MEN",
					"CONSERVATIVES",
					"GAMERS",
					"STRAIGHT MEN",
					"STRAIGHT WHITE MEN",
					"WHITE CHILDREN",
					"WHITE MEN",
					"r/KOTAKUINACTION USERS",
					"r/THEDONALD USERS",
					"CD PROJEKT RED DEVS"
				],
				guilty: [
					"CENSOR INNOCENT GAMES",
					"CENSOR JAPAN",
					"CENSOR THE BOOBS IN JAPANESE GAMES",
					"CENSOR THE RIGHT",
					"INFECT JAPAN WITH POLITICS",
					"INFECT JAPAN'S WATER SUPPLY WITH POLITICS",
					"INFECT THE WATER SUPPLY WITH POLITICS",
					"STOP BREXIT",
					"TAKE AWAY AMERICA'S GUNS",
					"TAKE AWAY BONER CULTURE",
					"TAKE AWAY SEXY GAMES",
					"TAKE AWAY WESTERN CULTURE",
					"DESTROY ANIME",
					"DESTROY JAPAN",
					"PROMOTE DEGENERACY",
					"PROMOTE THE LAST OF US PART 2",
					"DESTROY WESTERN CULTURE"
				],
				headlines: [
					"\"I'M GOING TO [guilty]\" SAYS [peopleA]?",
					"\"LIKING [media] MAKES YOU RACIST\" SAYS [peopleA]",
					"AMERICA has practically fallen to tyranny under the rule of [groupA].",
					"Are [adjA] [groupA] responsible for the FEMINIZATION of the WESTERN MALE?",
					"Are there [groupA] in JAPAN? - [peopleB] explains the PARADOX",
					"BIONICLE LORE - Pt. 1 of 14 as told by [adjA] [peopleB]",
					"DID [peopleB] PREDICT THE RISE OF [groupA]?",
					"DISGUSTING [groupA] FABRICATE a HITPIECE against [peopleB]",
					"Dear Game Developers, Please Don't Listen to [adjA] [peopleB].",
					"Despite what [groupA] say... [status] is the new COUNTER CULTURE!",
					"Did GEORGE ORWELL predict [peopleA] and NOT [peopleB]?",
					"Funding for [media] sequel CANCELLED by [adjA] [groupA]",
					"GOING THEIR OWN WAY: Japan REJECTS the dogma of [groupA]",
					"Is [media] sexist? [peopleA] THINKS SO",
					"JAPAN LOVES [peopleB]! HATES [peopleA]",
					"JAPAN has practically fallen to tyranny under the rule of [groupA].",
					"Japan will NEVER bow to [groupA]",
					"Japan will NEVER bow to [peopleA]",
					"Japan's new IMMIGRATION POLICY proves that [peopleB] was right all along!",
					"Keep [groupA] out of nerd CULTURE!",
					"President of Japan announces his decision to support [groupA]. It's over.",
					"SEXY WOMEN IN [media] TRIGGER [adjA] [groupA] - [clickbait]",
					"THE BIGGEST [peopleA] FAILS OF 2020",
					"THE LAST OF US PART 2 IS BRAINWASHING PEOPLE TO [guilty]",
					"THE WEST has practically fallen to tyranny under the rule of [groupA].",
					"THE [peopleA] EFFECT EXPLAINED",
					"The WAR against [peopleB] - [clickbait]",
					"The WAR against [media] - [clickbait]",
					"The fall of the Roman Empire was the doing of [adjA] [peopleA]!",
					"UNLIKE [peopleA], JAPAN ACTUALLY CARES ABOUT THE RIGHTS OF [adjB] [groupB]",
					"WHY ARE [groupA] SO OFFENDED BY [media]? [peopleB] EXPLAINS.",
					"WHY [peopleA] WILL NEVER WIN, EXPLAINED.",
					"Was [peopleA] responsible for the rise of Trump?",
					"Was [peopleB] the real SJW all along?",
					"Were [adjA] [groupA] responsible for the fall of the Roman Empire?",
					"Why do [groupA] HATE JAPAN SO MUCH?",
					"[groupA] ARE RUINING [media] - [peopleB] [action]",
					"[groupA] ATTACK MALE GAMERS, [peopleB] [action]",
					"[groupA] claim JAPAN has GAY PEOPLE in it - [peopleB] explains why that's FALSE",
					"[groupA] cry about SEXY WOMEN IN [media] - [peopleB] [action]",
					"[groupA] think they can [guilty]? [peopleB] [action]",
					"[groupA] want you to believe [peopleB] is LITERALLY HITLER?",
					"[peopleA] GOES AGAINST [peopleA] - THE LEFT EATS ITSELF",
					"[peopleA] SUCKS AT VIDEOGAMES. TRIES TO CRITIQUE THEM ANYWAYS. (what the fuck?)",
					"[peopleA] THINKS [status] MAKES YOU LITERALLY HITLER",
					"[peopleA] THINKS [status] MAKES YOU SEXIST",
					"[peopleA] TRIES TO [guilty] - [clickbait]",
					"[peopleA] gets DESTROYED in MASS DEBATE",
					"[peopleB] CALLS [groupA] OUT ON THEIR [adjA] AGENDA",
					"[peopleB] CALLS [peopleA] OUT ON THEIR AGENDA",
					"[peopleB] EXPLAINS THE STRUGGLE OF [status]",
					"[peopleB] EXPOSES [adjA] [groupA] - [clickbait]",
					"[peopleB] RESIGNS AFTER [groupA] CRUCIFY HIM FOR [status]",
					"[peopleB] gives SJWs on TWITTER PTSD - [clickbait]",
					"[peopleB] goes FULL SJW and makes it onto THE LIST?? HOW???",
					"[media] CAVES TO SJW [groupA]? [peopleB] explains WHY!",
					"[media] CREATOR HATES POLITICAL AGENDAS IN GAMES, FACES BACKLASH FROM [groupA]",
					"[media] GOES FULL SJW - [clickbait]",
					"[media] PUTS [peopleA] INTO A FRENZY",
					"[media] apparently isn't WOKE enough for [peopleA]...",
					"[media] is an allegory for the struggle of [adjB] [groupB].",
					"[media] is an allegory for the struggle of [groupB]."
				],
				media: [
					"ASSASSIN'S CREED",
					"CUPHEAD",
					"DARK SOULS",
					"DESTINY 2",
					"DOOM",
					"ELDER SCROLLS",
					"FALLOUT",
					"FORTNITE",
					"HALO",
					"LEAGUE OF LEGENDS",
					"MAGIC THE GATHERING",
					"METAL GEAR SOLID",
					"MINECRAFT",
					"OVERWATCH",
					"POKEMON",
					"SEKIRO",
					"STAR WARS",
					"STREET FIGHTER",
					"SUPER MARIO",
					"TEKKEN",
					"THE BIBLE",
					"THE LEGEND OF ZELDA",
					"THE WITCHER 3",
					"WARHAMMER",
					"WORLD OF WARCRAFT",
					"CYBERPUNK 2077"
				],
				peopleA: [
					"ALEXANDRIA OCASIO-CORTEZ",
					"ANITA SARKEESIAN",
					"ANTHONY BURCH",
					"BERNIE SANDERS",
					"BRIE LARSON",
					"HILLARY CLINTON",
					"KARL MARX",
					"KATHLEEN KENNEDY",
					"KOTAKU",
					"NEIL DRUCKMANN",
					"POLYGON",
					"RIAN JOHNSON",
					"ZOE QUINN"
				],
				peopleB: [
					"ADOLF HITLER",
					"ALEX JONES",
					"CHARLIE KIRK",
					"GEEKS&GAMERS",
					"IAN MILES CHEONG",
					"JORDAN PETERSON",
					"MY COCK",
					"MY DAD",
					"NIGEL FARAGE",
					"OUR GOOD LORD JESUS CHRIST",
					"PAUL JOSEPH WATSON",
					"PRESIDENT TRUMP",
					"RICHARD DAWKINS",
					"SAM HARRIS",
					"SARGON OF AKKAD",
					"THE QUARTERING",
					"BEN SHAPIRO",
					"COUNT DANKULA",
					"MILO YIANNOPOULOS",
					"MR METOKUR",
					"MY BEST FRIEND JOE",
					"RICHARD SPENCER",
					"THIS MATCHBOX WITH A TOY ALIEN INSIDE IT"
				],
				status: [
					"APPRECIATING JAPANESE WOMEN",
					"BEING A STRAIGHT WHITE MALE",
					"BEING A WHITE MALE",
					"BEING ALIVE",
					"BEING CIS",
					"BEING MALE",
					"BEING STRAIGHT",
					"HAVING OPINIONS",
					"NOT BEING GAY",
					"NOT BEING TRANSGENDER",
					"SIMPLY BEING A GAMER",
					"SIMPLY WANTING TO PRESERVE WHITE CULTURE",
					"WANTING TO DEFEND WESTERN CULTURE"
				]
			}
		};
	}),
	Code: (async function fakeNews () {
		const eligibleHeadlines = this.staticData.construct.headlines.filter(i => !this.data.previousHeadlines.includes(i));
		let headline = sb.Utils.randArray(eligibleHeadlines);

		this.data.previousHeadlines.push(headline);
		this.data.previousHeadlines.splice(this.staticData.repeats);

		while (headline.includes("[")) {
			headline = headline.replace(/\[(\w+)]/g, (total, type) => sb.Utils.randArray(this.staticData.construct[type]));
		}

		return {
			reply: headline
		};
	}),
	Dynamic_Description: null
};
