CREATE TABLE IF NOT EXISTS `data`.`Timezone` (
  `Abbreviation` VARCHAR(10) NOT NULL,
  `Name` VARCHAR(100) NOT NULL,
  `Offset` FLOAT NOT NULL DEFAULT 0,
  `Description` TEXT DEFAULT NULL,
  PRIMARY KEY (`Abbreviation`)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
;

INSERT INTO `Timezone`
(`Abbreviation`, `Name`, `Offset`, `Description`)
VALUES
	('ACDT', 'Australian Central Daylight Savings Time', 10.5, NULL),
	('ACST', 'Australian Central Standard Time', 9.5, NULL),
	('ACT', 'Acre Time', -5, NULL),
	('ACWST', 'Australian Central Western Standard Time (unofficial)', 8.75, NULL),
	('ADT', 'Atlantic Daylight Time', -3, NULL),
	('AEDT', 'Australian Eastern Daylight Savings Time', 11, NULL),
	('AEST', 'Australian Eastern Standard Time', 10, NULL),
	('AFT', 'Afghanistan Time', 4.5, NULL),
	('AKDT', 'Alaska Daylight Time', -8, NULL),
	('AKST', 'Alaska Standard Time', -9, NULL),
	('ALMT', 'Alma-Ata Time', 6, NULL),
	('AMST', 'Amazon Summer Time (Brazil)', -3, NULL),
	('AMT', 'Amazon Time (Brazil)', -4, NULL),
	('ANAT', 'Anadyr Time', 12, NULL),
	('AQTT', 'Aqtobe Time', 5, NULL),
	('ART', 'Argentina Time', -3, NULL),
	('AST', 'Atlantic Standard Time', -4, NULL),
	('AWST', 'Australian Western Standard Time', 8, NULL),
	('AZOST', 'Azores Summer Time', 0, NULL),
	('AZOT', 'Azores Standard Time', -1, NULL),
	('AZT', 'Azerbaijan Time', 4, NULL),
	('BDT', 'Brunei Time', 8, NULL),
	('BIOT', 'British Indian Ocean Time', 6, NULL),
	('BIT', 'Baker Island Time', -12, NULL),
	('BOT', 'Bolivia Time', -4, NULL),
	('BRST', 'Brasília Summer Time', -2, NULL),
	('BRT', 'Brasília Time', -3, NULL),
	('BST', 'British Summer Time', 1, NULL),
	('BTT', 'Bhutan Time', 6, NULL),
	('CAT', 'Central Africa Time', 2, NULL),
	('CCT', 'Cocos Islands Time', 6.5, NULL),
	('CDT', 'Central Daylight Time (North America)', -5, NULL),
	('CEST', 'Central European Summer Time', 2, NULL),
	('CET', 'Central European Time', 1, NULL),
	('CHADT', 'Chatham Daylight Time', 13.75, NULL),
	('CHAST', 'Chatham Standard Time', 12.75, NULL),
	('CHOST', 'Choibalsan Summer Time', 9, NULL),
	('CHOT', 'Choibalsan Standard Time', 8, NULL),
	('CHST', 'Chamorro Standard Time', 10, NULL),
	('CHUT', 'Chuuk Time', 10, NULL),
	('CIST', 'Clipperton Island Standard Time', -8, NULL),
	('CIT', 'Central Indonesia Time', 8, NULL),
	('CKT', 'Cook Island Time', -10, NULL),
	('CLST', 'Chile Summer Time', -3, NULL),
	('CLT', 'Chile Standard Time', -4, NULL),
	('COST', 'Colombia Summer Time', -4, NULL),
	('COT', 'Colombia Time', -5, NULL),
	('CST', 'Central Standard Time (North America)', -6, NULL),
	('CT', 'China Time', 8, NULL),
	('CVT', 'Cape Verde Time', -1, NULL),
	('CWST', 'Central Western Standard Time (Australia) unofficial', 8.75, NULL),
	('CXT', 'Christmas Island Time', 7, NULL),
	('DAVT', 'Davis Time', 7, NULL),
	('DDUT', 'Dumont d\'Urville Time', 10, NULL),
	('DFT', 'AIX-specific equivalent of Central European Time', 1, NULL),
	('EASST', 'Easter Island Summer Time', -5, NULL),
	('EAST', 'Easter Island Standard Time', -6, NULL),
	('EAT', 'East Africa Time', 3, NULL),
	('ECT', 'Eastern Caribbean Time (does not recognise DST)', -4, NULL),
	('EDT', 'Eastern Daylight Time (North America)', -4, NULL),
	('EEST', 'Eastern European Summer Time', 3, NULL),
	('EET', 'Eastern European Time', 2, NULL),
	('EGST', 'Eastern Greenland Summer Time', 0, NULL),
	('EGT', 'Eastern Greenland Time', -1, NULL),
	('EIT', 'Eastern Indonesian Time', 9, NULL),
	('EST', 'Eastern Standard Time (North America)', -5, NULL),
	('FET', 'Further-eastern European Time', 3, NULL),
	('FJT', 'Fiji Time', 12, NULL),
	('FKST', 'Falkland Islands Summer Time', -3, NULL),
	('FKT', 'Falkland Islands Time', -4, NULL),
	('FNT', 'Fernando de Noronha Time', -2, NULL),
	('GALT', 'Galápagos Time', -6, NULL),
	('GAMT', 'Gambier Islands Time', -9, NULL),
	('GET', 'Georgia Standard Time', 4, NULL),
	('GFT', 'French Guiana Time', -3, NULL),
	('GILT', 'Gilbert Island Time', 12, NULL),
	('GIT', 'Gambier Island Time', -9, NULL),
	('GMT', 'Greenwich Mean Time', 0, NULL),
	('GST', 'South Georgia and the South Sandwich Islands Time', -2, NULL),
	('GYT', 'Guyana Time', -4, NULL),
	('HAEC', 'Heure Avancée d\'Europe Centrale', 2, 'French language name for CEST'),
	('HDT', 'Hawaii–Aleutian Daylight Time', -9, NULL),
	('HKT', 'Hong Kong Time', 8, NULL),
	('HMT', 'Heard and McDonald Islands Time', 5, NULL),
	('HOVST', 'Hovd Summer Time', 8, '(not used from 2017-present)'),
	('HOVT', 'Hovd Time', 7, NULL),
	('HST', 'Hawaii–Aleutian Standard Time', -10, NULL),
	('ICT', 'Indochina Time', 7, NULL),
	('IDLW', 'International Day Line West time zone', -12, NULL),
	('IDT', 'Israel Daylight Time', 3, NULL),
	('IOT', 'Indian Ocean Time', 3, NULL),
	('IRDT', 'Iran Daylight Time', 4.5, NULL),
	('IRKT', 'Irkutsk Time', 8, NULL),
	('IRST', 'Iran Standard Time', 3.5, NULL),
	('IST', 'Indian Standard Time', 5.5, NULL),
	('JST', 'Japan Standard Time', 9, NULL),
	('KALT', 'Kaliningrad Time', 2, NULL),
	('KGT', 'Kyrgyzstan Time', 6, NULL),
	('KOST', 'Kosrae Time', 11, NULL),
	('KRAT', 'Krasnoyarsk Time', 7, NULL),
	('KST', 'Korea Standard Time', 9, NULL),
	('LINT', 'Line Islands Time', 14, NULL),
	('MAGT', 'Magadan Time', 12, NULL),
	('MART', 'Marquesas Islands Time', -8.5, NULL),
	('MAWT', 'Mawson Station Time', 5, NULL),
	('MDT', 'Mountain Daylight Time (North America)', -6, NULL),
	('MEST', 'Middle European Summer Time ', 2, 'Same timezone as CEST'),
	('MET', 'Middle European Time ', 1, 'Same timezone as CET'),
	('MHT', 'Marshall Islands Time', 12, NULL),
	('MIST', 'Macquarie Island Station Time', 11, NULL),
	('MIT', 'Marquesas Islands Time', -8.5, NULL),
	('MMT', 'Myanmar Standard Time', 6.5, NULL),
	('MSK', 'Moscow Time', 3, NULL),
	('MST', 'Mountain Standard Time (North America)', -7, NULL),
	('MUT', 'Mauritius Time', 4, NULL),
	('MVT', 'Maldives Time', 5, NULL),
	('MYT', 'Malaysia Time', 8, NULL),
	('NCT', 'New Caledonia Time', 11, NULL),
	('NDT', 'Newfoundland Daylight Time', -1.5, NULL),
	('NFT', 'Norfolk Island Time', 11, NULL),
	('NOVT', 'Novosibirsk Time ', 7, NULL),
	('NPT', 'Nepal Time', 5.75, NULL),
	('NST', 'Newfoundland Standard Time', -2.5, NULL),
	('NT', 'Newfoundland Time', -2.5, NULL),
	('NUT', 'Niue Time', -11, NULL),
	('NZDT', 'New Zealand Daylight Time', 13, NULL),
	('NZST', 'New Zealand Standard Time', 12, NULL),
	('OMST', 'Omsk Time', 6, NULL),
	('ORAT', 'Oral Time', 5, NULL),
	('PDT', 'Pacific Daylight Time (North America)', -7, NULL),
	('PET', 'Peru Time', -5, NULL),
	('PETT', 'Kamchatka Time', 12, NULL),
	('PGT', 'Papua New Guinea Time', 10, NULL),
	('PHOT', 'Phoenix Island Time', 13, NULL),
	('PHT', 'Philippine Time', 8, NULL),
	('PKT', 'Pakistan Standard Time', 5, NULL),
	('PMDT', 'Saint Pierre and Miquelon Daylight Time', -2, NULL),
	('PMST', 'Saint Pierre and Miquelon Standard Time', -3, NULL),
	('PONT', 'Pohnpei Standard Time', 11, NULL),
	('PST', 'Pacific Standard Time (North America)', -8, NULL),
	('PYST', 'Paraguay Summer Time', -3, NULL),
	('PYT', 'Paraguay Time', -4, NULL),
	('RET', 'Réunion Time', 4, NULL),
	('ROTT', 'Rothera Research Station Time', -3, NULL),
	('SAKT', 'Sakhalin Island Time', 11, NULL),
	('SAMT', 'Samara Time', 4, NULL),
	('SAST', 'South African Standard Time', 2, NULL),
	('SBT', 'Solomon Islands Time', 11, NULL),
	('SCT', 'Seychelles Time', 4, NULL),
	('SDT', 'Samoa Daylight Time', -10, NULL),
	('SGT', 'Singapore Time', 8, NULL),
	('SLST', 'Sri Lanka Standard Time', 5.5, NULL),
	('SRET', 'Srednekolymsk Time', 11, NULL),
	('SRT', 'Suriname Time', -3, NULL),
	('SST', 'Singapore Standard Time', 8, NULL),
	('SYOT', 'Showa Station Time', 3, NULL),
	('TAHT', 'Tahiti Time', -10, NULL),
	('TFT', 'French Southern and Antarctic Time', 5, NULL),
	('THA', 'Thailand Standard Time', 7, NULL),
	('TJT', 'Tajikistan Time', 5, NULL),
	('TKT', 'Tokelau Time', 13, NULL),
	('TLT', 'Timor Leste Time', 9, NULL),
	('TMT', 'Turkmenistan Time', 5, NULL),
	('TOT', 'Tonga Time', 13, NULL),
	('TRT', 'Turkey Time', 3, NULL),
	('TVT', 'Tuvalu Time', 12, NULL),
	('ULAST', 'Ulaanbaatar Summer Time', 9, NULL),
	('ULAT', 'Ulaanbaatar Standard Time', 8, NULL),
	('UTC', 'Coordinated Universal Time', 0, NULL),
	('UYST', 'Uruguay Summer Time', -2, NULL),
	('UYT', 'Uruguay Standard Time', -3, NULL),
	('UZT', 'Uzbekistan Time', 5, NULL),
	('VET', 'Venezuelan Standard Time', -4, NULL),
	('VLAT', 'Vladivostok Time', 10, NULL),
	('VOLT', 'Volgograd Time', 4, NULL),
	('VOST', 'Vostok Station Time', 6, NULL),
	('VUT', 'Vanuatu Time', 11, NULL),
	('WAKT', 'Wake Island Time', 12, NULL),
	('WAST', 'West Africa Summer Time', 2, NULL),
	('WAT', 'West Africa Time', 1, NULL),
	('WEST', 'Western European Summer Time', 1, NULL),
	('WET', 'Western European Time', 0, NULL),
	('WIT', 'Western Indonesian Time', 7, NULL),
	('WST', 'Western Standard Time', 8, NULL),
	('YAKT', 'Yakutsk Time', 9, NULL),
	('YEKT', 'Yekaterinburg Time', 5, NULL)
;
