approvedGitRepositories:
  - "**"

enableGlobalCache: true

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: "7d"
npmPreapprovedPackages: ["mariadb", "got"] # remove when 3.5.4 is properly released (it was re-released on 2026-09-01)
