CREATE TABLE IF NOT EXISTS `chat_data`.`User_Alias` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(32) NOT NULL,
  `Discord_ID` VARCHAR(20) DEFAULT NULL,
  `Mixer_ID` VARCHAR(16) DEFAULT NULL,
  `Twitch_ID` VARCHAR(16) DEFAULT NULL,
  `Started_Using` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `Data` TEXT DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `Name` (`Name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
